version: '3.4'

#networks:
#  default:
#   driver: bridge
services:
  api:
    depends_on:
      - app
      - db
    build: ./backend
#    networks:
#      - default
    volumes:
      - ./backend/api/:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    env_file:
      - ./backend/.env

  db:
    image: postgres
    restart: always
#    networks:
#      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
    - "5432:5432"

  app:
    build: ./frontend/react-docker
    command: ["npm", "start"]
    volumes:
      - ./frontend/react-docker:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:3000"

volumes:
  postgres_data: